package android.ext;

import android.content.pm.ApplicationInfo;
import android.content.pm.PackageInfo;
import android.content.pm.PackageManager.NameNotFoundException;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;

public class qm extends Writer {
    final Script.Consts a;
    private final Writer b;
    private final String c;

    public qm(String s) {
        File file0 = new File(s);
        File file1 = file0.getParentFile();
        if(file1 != null) {
            file1.mkdirs();
        }
        this.c = s;
        this.b = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(file0)));
        this.c();
        this.a = Script.a(null);
    }

    private void a(String s, Throwable throwable0) {
        la.b(("Failed write text to record file: " + this.c + '\n' + s), throwable0);
        this.a();
        rx.a(new qn(this, throwable0));
    }

    public void a() {
        MainService.instance.a(this);
        try {
            this.b.close();
        }
        catch(IOException iOException0) {
            la.b(("Failed close record to: " + this.c), iOException0);
        }
        Tools.b((Tools.c(0x7F0702E6) + ": " + this.c));  // string:record_ended "Recording completed:"
    }

    public String b() {
        return this.c;
    }

    private void c() {
        String s = "-- Script generated by GameGuardian %gg_ver% (%gg_build%) at %now% for %t_name% [%t_pkg% %t_ver% (%t_build%)]\n-- Lua help: http://gameguardian.net/help/\n\n-- options\nlocal scriptName = [=====[Script for %t_name% %t_ver%]=====]\nlocal scriptVersion = \'1.0.0\'\nlocal scriptAuthor = \'User\'\nlocal startToast = \'\'\n-- 0 - no check; 1 - check package only, 2 - check package and build\nlocal checkTarget = 0\n\nlocal targetName = [=====[%t_name%]=====]\nlocal targetPkg = \'%t_pkg%\'\nlocal targetVersion = [=====[%t_ver%]=====]\nlocal targetBuild = %t_build%\n\n-- functions\n\n-- init\ngg.require(\'%gg_ver%\', %gg_build%)\n\nif startToast ~= \'\' then startToast = \'\\n\'..startToast end\ngg.toast(scriptName..\' v\'..scriptVersion..\' by \'..scriptAuthor..startToast)\n\nif checkTarget ~= 0 then\n\tlocal info = gg.getTargetInfo()\n\tlocal check = false\n\tlocal current = false\n\tif checkTarget >= 1 then\n\t\tcheck = targetPkg\n\t\tcurrent = info.packageName\n\tend\n\tif checkTarget >= 2 then\n\t\tcheck = check..\' \'..targetVersion..\' (\'..targetBuild..\')\'\n\t\tcurrent = current..\' \'..info.versionName..\' (\'..info.versionCode..\')\'\n\tend\n\tif check ~= current then\n\t\tgg.alert(\'This script for \"\'..targetName..\'\" [\'..check..\'].\\nYou select \"\'..info.label..\'\" [\'..current..\'].\\nNow script exit.\')\n\t\tos.exit()\n\tend\nend\nlocal revert = nil\n\n-- main code\n".replace("%gg_ver%", 101.099998f).replace("%gg_build%", "16142").replace("%now%", new SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.US).format(new Date()));
        qh qh0 = MainService.instance.ap;
        if(qh0 != null) {
            String s1 = qh0.c;
            s = s.replace("%t_pkg%", s1);
            try {
                PackageInfo packageInfo0 = Tools.d(s1, 0);
                if(packageInfo0 != null) {
                    if(packageInfo0.versionName != null) {
                        s = s.replace("%t_ver%", packageInfo0.versionName);
                    }
                    s = s.replace("%t_build%", Integer.toString(packageInfo0.versionCode));
                    ApplicationInfo applicationInfo0 = packageInfo0.applicationInfo;
                    if(applicationInfo0 != null) {
                        String s2 = Tools.a(applicationInfo0);
                        if(s2 != null) {
                            s = s.replace("%t_name%", s2);
                        }
                    }
                }
            }
            catch(PackageManager.NameNotFoundException packageManager$NameNotFoundException0) {
                la.b(("Pkg not found: " + s1), packageManager$NameNotFoundException0);
            }
        }
        this.b.write(s);
    }

    @Override
    public void close() {
    }

    @Override
    public void flush() {
    }

    @Override
    public void write(String s) {
        try {
            this.b.write(s);
        }
        catch(Throwable throwable0) {
            this.a(s, throwable0);
        }
    }

    @Override
    public void write(char[] arr_c, int v, int v1) {
    }
}

