package luaj;

import android.content.Context;
import android.ext.Tools;
import java.io.EOFException;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.PrintStream;
import java.nio.channels.FileChannel;
import lasm.a;
import lasm.g;
import luaj.lib.BaseLib;
import luaj.lib.DebugLib;
import luaj.lib.PackageLib;
import luaj.lib.j;

public class Globals extends LuaTable {
    public boolean a;
    public int b;
    public long c;
    public int d;
    public PrintStream e;
    public PrintStream f;
    public j g;
    public LuaThread h;
    public BaseLib i;
    public PackageLib j;
    public DebugLib k;
    public c l;
    public b m;
    public e n;
    private String q;
    private String r;

    public Globals() {
        this.a = true;
        this.b = 0;
        this.q = null;
        this.c = 0L;
        this.d = 0;
        this.e = System.out;
        this.f = System.err;
        this.h = new LuaThread(this);
        this.r = null;
    }

    public LuaValue a(InputStream inputStream0, String s, String s1, LuaValue luaValue0) {
        LuaValue luaValue1;
        try {
            try {
                al al0 = this.a(inputStream0, s, s1);
                luaValue1 = this.l.a(al0, s, luaValue0);
                goto label_18;
            }
            catch(o o0) {
            }
            catch(EOFException eOFException0) {
                goto label_6;
            }
            catch(Exception exception0) {
                goto label_11;
            }
            throw o0;
        label_6:
            luaValue1 = Globals.a("truncated precompiled chunk", eOFException0);
        }
        catch(Throwable throwable0) {
            goto label_16;
        }
        try {
            inputStream0.close();
        }
        catch(IOException unused_ex) {
        }
        return luaValue1;
        try {
        label_11:
            luaValue1 = Globals.a(("load " + s + ": " + exception0), exception0);
        }
        catch(Throwable throwable0) {
            goto label_16;
        }
        try {
            inputStream0.close();
        }
        catch(IOException unused_ex) {
        }
        return luaValue1;
        try {
        label_16:
            inputStream0.close();
        }
        catch(IOException unused_ex) {
        }
        throw throwable0;
        try {
        label_18:
            inputStream0.close();
        }
        catch(IOException unused_ex) {
        }
        return luaValue1;
    }

    public al a(InputStream inputStream0, String s) {
        if(this.m == null) {
            Globals.f("No compiler.");
        }
        return this.m.a(d.a(inputStream0).a(true), s);
    }

    public al a(InputStream inputStream0, String s, String s1) {
        InputStream inputStream2;
        if(s1.indexOf(98) >= 0) {
            if(this.n == null) {
                Globals.f("No undumper.");
            }
            byte[] arr_b = new byte[4];
            int v = inputStream0.read(arr_b);
            if(arr_b[0] == f.c[0] && arr_b[1] == f.c[1] && arr_b[2] == f.c[2] && arr_b[3] == f.c[3]) {
                al al0 = this.n.a(inputStream0, s);
                if(inputStream0 instanceof luaj.lib.b) {
                    InputStream inputStream1 = ((luaj.lib.b)inputStream0).a();
                    if(inputStream1 instanceof FileInputStream) {
                        long v1 = ((luaj.lib.b)inputStream0).b();
                        if(v1 < ((FileInputStream)inputStream1).getChannel().size()) {
                            al0.C = (int)v1;
                            return al0;
                        }
                    }
                }
                else if(inputStream0 instanceof FileInputStream) {
                    FileChannel fileChannel0 = ((FileInputStream)inputStream0).getChannel();
                    long v2 = fileChannel0.position();
                    if(v2 < fileChannel0.size()) {
                        al0.C = (int)v2;
                        return al0;
                    }
                }
                return al0;
            }
            if(v > 0) {
                d d0 = d.a(inputStream0);
                d0.unread(arr_b, 0, v);
                inputStream0 = d0;
            }
        }
        if(s1.indexOf(0x74) < 0) {
            throw new o("attempt to load a text chunk (mode is \'" + s1 + "\'");
        }
        byte[] arr_b1 = new byte[61];
        int v3 = inputStream0.read(arr_b1);
        if(v3 > 0) {
            inputStream2 = d.a(inputStream0);
            ((d)inputStream2).unread(arr_b1, 0, v3);
        }
        else {
            inputStream2 = inputStream0;
        }
        if(new String(arr_b1).equals("; --[=========[ Lua assembler file generated by GameGuardian ")) {
            try {
                return new a(inputStream2).a();
            }
            catch(g g0) {
                throw new o("Failed assemble: " + g0.getMessage(), g0);
            }
        }
        if(arr_b1[0] == f.c[0] && arr_b1[1] == f.c[1] && arr_b1[2] == f.c[2] && arr_b1[3] == f.c[3]) {
            throw new o("attempt to load a binary chunk (mode is \'" + s1 + "\')");
        }
        return this.a(inputStream2, s);
    }

    public void a(long v) {
        this.c += v;
        if(this.c >= 0x40000000L) {
            Context context0 = Tools.e();
            throw new o("Too many write to files: " + Tools.a(context0, this.c) + "; last: " + Tools.a(context0, v));
        }
    }

    public void a(String s) {
        if(s == null) {
        label_3:
            ++this.b;
            if(this.b >= 0x400) {
                throw new o("Too many open files: " + this.b + "; last: " + s);
            }
        }
        else if(!s.equals(this.q)) {
            this.q = s;
            goto label_3;
        }
    }

    @Override  // luaj.LuaValue
    public Globals c() {
        return this;
    }

    public void c(String s) {
        this.r = s;
    }

    public LuaValue c_(String s) {
        try {
            InputStream inputStream0 = this.g.c(s);
            String s1 = this.d(s).getAbsolutePath();
            LuaValue luaValue0 = this.a(inputStream0, "@" + s1, "bt", this);
            if(luaValue0 instanceof LuaClosure) {
                ((LuaClosure)luaValue0).d = s1;
            }
            return luaValue0;
        }
        catch(Exception exception0) {
            return Globals.a(("load " + s + ": " + exception0), exception0);
        }
    }

    public File d(String s) {
        String s1 = this.r;
        return s1 == null || s.length() != 0 && s.charAt(0) == 0x2F ? new File(s) : new File(s1, s);
    }
}

